# Basic

### Q1. Create a 1D array of numbers from 0 to 9 Desired output

In [1]:
import numpy as np
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


### Q. Create a 3×3 numpy array of all True’s

In [4]:
import numpy as np
arr=np.full((3,3),True,dtype=bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### Q. Extract all odd numbers from arr Input:

In [11]:
import numpy as np
arr=np.array([6,7,89,44,56,7,8,3,21])
arr=arr[(arr%2!=0)]
print(arr)

[ 7 89  7  3 21]


### Q. Replace all odd numbers in arr with -1 Input:


In [14]:
import numpy as np
arr=np.array([6,7,89,44,56,7,8,3,21])

arr[arr%2==1]=-1
print(arr)

[ 6 -1 -1 44 56 -1  8 -1 -1]


### Q. Replace all odd numbers in arr with -1 without changing arr Input:

In [16]:
import numpy as np
arr=np.array([6,7,89,44,56,7,8,3,21])
temp=arr.copy()
temp[temp%2==1]=-1
print("Original Array:",arr)
print("Replaced array:",temp)

Original Array: [ 6  7 89 44 56  7  8  3 21]
Replaced array: [ 6 -1 -1 44 56 -1  8 -1 -1]


### Q. Convert a 1D array to a 2D array with 2 rows Input:

In [19]:
import numpy as np
arr=np.arange(10)
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Q. Stack arrays a and b vertically Input

In [29]:
import numpy as np

a=np.arange(10).reshape(2,-1)
b=np.repeat(1,10).reshape(2,-1)

np.concatenate([a,b], axis=0)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### Q. stack arrays a and b hrizontally input

In [31]:
import numpy as np

a=np.arange(10).reshape(2,-1)
b=np.repeat(1,10).reshape(2,-1)

np.concatenate([a,b], axis=1)


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a. Input:

In [37]:
import numpy as np
a=np.arange(10,14)
b=np.r_[np.repeat(a,3),np.tile(a,3)]
print(b)

[10 10 10 11 11 11 12 12 12 13 13 13 10 11 12 13 10 11 12 13 10 11 12 13]


### Q. Get the common items between a and b Input:

In [39]:
import numpy as np
a=np.arange(10,15)
b=np.arange(10,18)
np.intersect1d(a,b)


array([10, 11, 12, 13, 14])

### Q. From array a remove all items present in array b Input:

In [44]:
import numpy as np
a=np.arange(10,19)
b=np.arange(10,16)
np.setdiff1d(a,b)

array([16, 17, 18])

### Q.  Get all items between 5 and 10 from a. Input:

In [50]:
import numpy as np
a=np.arange(5,19)
arr= a[(a>=5) & (a<=10)]
print(arr)


[ 5  6  7  8  9 10]


### Q. Swap columns 1 and 2 in the array arr.

In [54]:
import numpy as np
a=np.arange(9).reshape(3,3)
a[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

### Q. Swap rows 1 and 2 in the array arr

In [56]:
import numpy as np
a=np.arange(9).reshape(3,3)
a[[0,2,1],:]

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

### Q. Reverse the rows of a 2D array arr

In [58]:
import numpy as np
a=np.arange(9).reshape(3,3)
a[[2,1,0],:]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

### Q. Reverse the columns of a 2D array arr.

In [60]:
import numpy as np
a=np.arange(9).reshape(3,3)
a[:,[2,1,0]]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

### Q. Create a 2D array of shape 5×3 to contain random decimal numbers between 5 and 10

In [65]:
import numpy as np
a=np.random.randint(5,10,(5,3))
a

array([[9, 9, 8],
       [7, 9, 6],
       [6, 8, 5],
       [8, 5, 5],
       [6, 5, 9]])